### PR TITLE
Added support for followupEvent to the Fulfilment class.

### PR DESCRIPTION
**Pull request by nikodem911**
API AI supports triggering intents via Events which can be returned from the webhook as described here:
https://api.ai/docs/fulfillment#section-format-of-response-from-the-service

The Fulfillment class was modified and a field containing AIEvent was added.

### CODE REVIEW

**Comment by folomeev** [comment]
Thank you for your pull request!
Please remove version change in `pom.xml` files. This is not required for the fix and in fact not related to the issue.

**Comment by nikodem911** [comment]
The version bump has been reverted.
I'd like to use the changes from the pull request in my project.
When could the new version of the API be released?

**Comment by nikodem911** [comment]
What else needs to be done to have the pull request merged?

**Comment by folomeev** [comment]
You changes are available within latest release (version 1.6.11).

**Comment by nikodem911** [comment]
Great, thanks!

**Pull request merged**
